/*
 * Virtual Patient List Api
 *
 * Virtual Patient List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_virtual_patient_list

import (
	"github.com/gin-gonic/gin"
)

type VirtualPatientListAPI interface {


    // CreateVirtualPatient Post /api/virtual-patient-list/entries
    // Creates a new virtual patient 
     CreateVirtualPatient(c *gin.Context)

    // DeleteVirtualPatient Delete /api/virtual-patient-list/entries/:virtualPatientId
    // Deletes a virtual patient 
     DeleteVirtualPatient(c *gin.Context)

    // GetVirtualPatientList Get /api/virtual-patient-list/entries
    // Provides the virtual patient list 
     GetVirtualPatientList(c *gin.Context)

    // UpdateVirtualPatient Put /api/virtual-patient-list/entries/:virtualPatientId
    // Updates a virtual patient 
     UpdateVirtualPatient(c *gin.Context)

}