/*
 * Virtual Patient List Api
 *
 * Virtual Patient List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_virtual_patient_list

import (
	"github.com/gin-gonic/gin"
)

type VirtualPatientListAPI interface {


    // GetVirtualPatientList Get /api/virtual-patient-list/entries
    // Provides the virtual patient list 
     GetVirtualPatientList(c *gin.Context)

}