/*
 * Virtual Patient List Api
 *
 * Virtual Patient List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_virtual_patient_list

type VirtualPatient struct {

	// Unique identifier of the virtual patient
	Id string `json:"id"`

	// Name of the virtual patient
	Name string `json:"name"`

	// MongoDB record identifier
	RecordId string `json:"recordId"`

	// Difficulty of the virtual patient. 1 is the easiest, 5 is the hardest.
	Difficulty int32 `json:"difficulty"`

	// List of symptoms the virtual patient is experiencing
	Symptoms []string `json:"symptoms"`

	// Medical history and current condition description
	Anamnesis string `json:"anamnesis"`
}
