apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
  - name: xprikryl-ambulance-vp-api-mongodb-init
    files:
      - params/init-db.js
  - name: xprikryl-ambulance-vp-api-config
    literals:
      - database=xprikryl-ambulance
      - collection=virtual-patients
patches:
- path: patches/webapi.deployment.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: xprikryl-ambulance-vp-api